def calc_num_lines(wildcards):
    # wildcards.num_records를 정수로 변환합니다.
    num_records = int(wildcards.num_records)

    # 줄 수를 계산합니다 (레코드 * 4).
    num_lines = num_records * 4

    return num_lines

rule all:
    input:
        "big.subset25.fastq"

rule subset:
    input:
        "big.fastq"
    output:
        "big.subset{num_records}.fastq"
    params:
        num_lines = calc_num_lines
    shell: """
        head -{params.num_lines} {input} > {output}
    """
