# ANCHOR: 제약 조건
# 모든 .txt 파일 일치 - 제약 조건 없음
all_files = glob_wildcards("{filename}.txt").filename

# 이 디렉터리의 모든 .txt 파일만 일치 - / 방지
this_dir_files = glob_wildcards("{filename,[^/]+}.txt").filename

# 이름에 마침표가 하나만 있는 모든 파일 일치 - . 방지
prefix_only = glob_wildcards("{filename,[^.]+}.txt").filename

# 이 디렉터리에서 이름에 마침표가 하나만 있는 모든 파일 일치
# / 및 . 방지
prefix_and_dir_only = glob_wildcards("{filename,[^./]+}.txt").filename
# ANCHOR_END: 제약 조건

print(all_files)
print(this_dir_files)
print(prefix_only)
print(prefix_and_dir_only)

assert set(all_files) == { 'file1.subset', 'file1', 'subdir/file2', 'subdir/file2.subset', 'subdir/nested/file3' }
assert set(this_dir_files) == { 'file1.subset', 'file1' }
assert set(prefix_only) == { 'file1', 'subdir/file2', 'subdir/nested/file3' }
assert prefix_and_dir_only == ['file1']
